apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-policies
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: demo-policies
    app.kubernetes.io/component: network-policy
spec:
  project: default

  source:
    repoURL: https://github.com/ciscocpa/demo-gitops-network-policy.git
    targetRevision: main
    path: policies
    directory:
      recurse: true
      include: '*.yaml'
      exclude: '.gitkeep'

  destination:
    server: https://kubernetes.default.svc
    namespace: demo-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Sync wave: Deploy policies after apps
  syncWave: 10
