---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: tenant-b
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: backend-service
---
apiVersion: v1
kind: Pod
metadata:
  name: backend-service
  namespace: tenant-b
  labels:
    app: backend-service
spec:
  containers:
  - name: backend-service
    image: docker.io/cilium/json-mock:latest
    ports:
    - containerPort: 8080
      protocol: TCP