---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: tenant-a
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: frontend-service
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend-service
  namespace: tenant-a
  labels:
    app: frontend-service
spec:
  containers:
  - name: frontend-service
    image: docker.io/cilium/json-mock:latest
    ports:
    - containerPort: 8080
      protocol: TCP